---
apiVersion: v1
kind: Secret
metadata:
  name: quay-config-bundle-ldap
  namespace: quay-enterprise
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  config.yaml: |
    {{- toYaml .Values.mgmt.quay.param | nindent 4 }}
    SUPERUSERS:
    - automation
  custom-cert.crt: {{ .Values.mgmt.authentication.ldap.crt }}