{{- $apps := .Values.mgmt.apps -}}
{{- range $vm := .Values.mgmt.idm }}
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  annotations:
    name.os.template.kubevirt.io/rhel9.0: Red Hat Enterprise Linux 9.0 or higher
    argocd.argoproj.io/sync-wave: "20"
  labels:
    app: "{{ $vm.app_name }}"
    flavor.template.kubevirt.io/medium: "true"
    os.template.kubevirt.io/rhel9.0: "true"
    workload.template.kubevirt.io/server: "true"
  name: "{{ $vm.name }}"
  namespace: "{{ $apps.ns }}"
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1alpha1
    kind: DataVolume
    metadata:
      creationTimestamp: null
      name: "{{ $vm.hostname }}-rootdisk-0"
    spec:
      pvc:  #Set acccessModes to RWX and volumeMode to block for live migration and VM pod eviction
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 50Gi
        storageClassName: ocs-storagecluster-ceph-rbd
        volumeMode: Block
      source:
        http:
          url: http://{{ $apps.provisioner_ip }}/{{ $vm.qcow }}
  running: true
  template:
    metadata:
      labels:
        flavor.template.kubevirt.io/medium: "true"
        kubevirt.io/domain: "{{ $vm.domain }}"
        kubevirt.io/size: large
        os.template.kubevirt.io/rhel9.0: "true"
        vm.kubevirt.io/name: "{{ $vm.domain }}"
        workload.template.kubevirt.io/server: "true"
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      domain:
        firmware:
          uuid: "{{ $vm.uuid }}"
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: cloudinitdisk
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
          interfaces:
            - bridge: {}
              model: virtio
              name: nic-1
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel9.0.0
        resources:
          requests:
            memory: 8Gi
      evictionStrategy: LiveMigrate
      hostname: "{{ $vm.name }}"
      networks:
        - multus:
            networkName: "{{ $apps.nad_name }}"
          name: nic-1
      terminationGracePeriodSeconds: 180
      volumes:
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              ssh_pwauth: True
              user: {{ $vm.user }}
              password: {{ $vm.password }}
              chpasswd:
                expire: false
              hostname: {{ $vm.name }}
              fqdn: {{ $vm.hostname }}
              prefer_fqdn_over_hostname: true
              timezone: Europe/Madrid
              ssh_authorized_keys:
              - {{ $vm.ssh_authorized_key }}
            networkData: |
              version: 2
              ethernets:
                eth0:
                  addresses:
                  - "{{ $vm.ip }}/{{ $apps.subnet_len }}"
                  gateway4: "{{ $apps.subnet_gw }}"
                  nameservers:
                    search: [{{ $apps.domain }}]
                    addresses: [{{ $apps.dns_server_ip }}]
          name: cloudinitdisk
        - dataVolume:
            name: "{{ $vm.hostname }}-rootdisk-0"
          name: rootdisk
{{- end }}
