---
global:
  pattern: mgmt-cluster

  options:
    useCSV: true
    syncPolicy: Automatic
    installPlanApproval: Manual
    autoApproveManualInstallPlans: true

  params:
    job_image: registry.redhat.io/openshift4/ose-tools-rhel8:latest

main:
  clusterGroupName: hub
