{{- if not (eq .Values.enabled "plumbing") }}
{{- range $node := .Values.clusterGroup.nodes }}
apiVersion: v1
kind: Node
metadata:
  {{- range $k, $v := $node }}{{- /* We loop here even though the map has always just one key */}}
  name: {{ $k }}
  labels:
    argocd.argoproj.io/managed-by: {{ $.Values.global.pattern }}-{{ $.Values.clusterGroup.name }}
    {{- if $v.labels }}
    {{- range $key, $value := $v.labels }} {{- /* We loop here even though the map has always just one key */}}
    {{ $key }}: {{ $value | default "" | quote }}
    {{- end }}
    {{- end }}
  {{- end }}{{- /* range $k, $v := $node */}}
---
{{- end -}}
{{- end -}}
