---
apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  htpasswd: |-
    {{- range $key, $val := .Values.mgmt.authentication.htpasswd }}
    {{ $key }}:{{ $val }}
    {{- end }}
