---
apiVersion: v1
kind: Secret
metadata:
  name: kubeadmin
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: Replace=true
type: Opaque
data: {}
