---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-auth-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  bindPassword: {{ .Values.mgmt.authentication.ldap.bind_password }}
