---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-ca-cert
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  ca.crt: {{ .Values.mgmt.authentication.ldap.crt }}
