---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
{{- if .Values.mgmt.authentication.htpasswd }}
  - htpasswd:
      fileData:
        name: htpasswd-secret
    mappingMethod: claim
    name: htpasswd
    type: HTPasswd
{{- end }}
{{- if .Values.mgmt.authentication.ldap }}
  - name: idm-ldap
    mappingMethod: add
    type: LDAP
    ldap:
      attributes:
        id:
        - dn
        email:
        - mail
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: "{{ .Values.mgmt.authentication.ldap.bind_dn }}"
      bindPassword:
        name: "ldap-auth-secret"
      ca:
        name: ldap-ca-cert
      insecure: false
      url: "ldap://{{ .Values.mgmt.authentication.ldap.url }}/{{ .Values.mgmt.authentication.ldap.users_base_dn }}?uid?sub?(memberOf={{ .Values.mgmt.authentication.ldap.group_membership }})"
{{- end }}

