apiVersion: v1
kind: Service
metadata:
  name: stf-kafka-adapter-svc
  namespace: prom-kafka-adapter
  labels:
    app: stf-prometheus-kafka-adapter
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: stf-prometheus-kafka-adapter

