apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
metadata:
  name: default
  namespace: service-telemetry
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  clouds:
{{- range $cloudName := $.Values.mgmt.stf.cloudNames }}
    - metrics:
        collectors:
          - bridge:
              ringBufferCount: 15000
              ringBufferSize: 16384
              verbose: false
            collectorType: collectd
            debugEnabled: false
            subscriptionAddress: collectd/{{ $cloudName }}-telemetry
          - bridge:
              ringBufferCount: 15000
              ringBufferSize: 16384
              verbose: false
            collectorType: ceilometer
            debugEnabled: false
            subscriptionAddress: anycast/ceilometer/{{ $cloudName }}-metering.sample
          - bridge:
              ringBufferCount: 15000
              ringBufferSize: 16384
              verbose: false
            collectorType: sensubility
            debugEnabled: false
            subscriptionAddress: sensubility/{{ $cloudName }}-telemetry
      name: {{ $cloudName }}
{{- end }}
  highAvailability:
    enabled: false
  observabilityStrategy: none
  transports:
    qdr:
      auth: none
      certificates:
        caCertDuration: 70080h
        endpointCertDuration: 70080h
      enabled: true
      web:
        enabled: false
