kind: Secret
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: git-creds
  namespace: ztp
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  password: {{ .Values.mgmt.gitops.core_ztp_repoToken }}
  url: {{ .Values.mgmt.gitops.repoURL }}
  username: not-used
type: Opaque

