---
apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: controler
  namespace: ansible-automation-platform
spec:
  no_log: false
  create_preload_data: true
  route_tls_termination_mechanism: Edge
  ingress_type: Route
  garbage_collect_secrets: false
  loadbalancer_port: 80
  image_pull_policy: IfNotPresent
  projects_storage_size: 8Gi
  task_privileged: false
  projects_storage_access_mode: ReadWriteMany
  postgres_storage_class: ocs-storagecluster-ceph-rbd
  projects_persistence: false
  replicas: 1
  admin_user: admin
  loadbalancer_protocol: http
  nodeport_port: 30080
  ldap_cacert_secret: ldap-ca-cert
  #ldap_password_secret: ldap-auth-secret
  extra_settings:
  - setting: AUTH_LDAP_SERVER_URI
    value: >-
      "ldaps://idm-serv.{{ .Values.mgmt.cluster.name }}.{{ .Values.mgmt.cluster.location }}.{{ .Values.mgmt.cluster.domain }}:636"
  - setting: AUTH_LDAP_BIND_DN
    value: >-
      "uid=ansible-bind-user,cn=users,cn=accounts,dc={{ .Values.mgmt.cluster.name }},dc={{ .Values.mgmt.cluster.location }},dc={{ .Values.mgmt.cluster.domain }}"
  # todo: use a secret instead
  - setting: AUTH_LDAP_BIND_PASSWORD
    value: >-
      "Jn6E7Mpsi9fb07cJzEwbJw=="
  - setting: AUTH_LDAP_USER_SEARCH
    value: >-
      LDAPSearch("cn=users,cn=accounts,dc={{ .Values.mgmt.cluster.name }},dc={{ .Values.mgmt.cluster.location }},dc={{ .Values.mgmt.cluster.domain }},ldap.SCOPE_SUBTREE,"(uid=%(user)s)",)
  - setting: AUTH_LDAP_GROUP_SEARCH
    value: >-
      LDAPSearch("cn=groups,cn=accounts,dc={{ .Values.mgmt.cluster.name }},dc={{ .Values.mgmt.cluster.location }},dc={{ .Values.mgmt.cluster.domain }},ldap.SCOPE_SUBTREE,"(objectClass=ipaUserGroup)",)
  - setting: AUTH_LDAP_USER_ATTR_MAP
    value: {
      "first_name": "givenName",
      "last_name": "sn",
      "email": "mail"
    }
  - setting: AUTH_LDAP_USER_FLAGS_BY_GROUP
    value:
      is_superuser:
      - >-
        cn=ansibleadmins,cn=groups,cn=accounts,dc={{ .Values.mgmt.cluster.name }},dc={{ .Values.mgmt.cluster.location }},dc={{ .Values.mgmt.cluster.domain }}
  - setting: AUTH_LDAP_REQUIRE_GROUP
    value: >-
      "cn=ansibleusers,cn=groups,cn=accounts,dc={{ .Values.mgmt.cluster.name }},dc={{ .Values.mgmt.cluster.location }},dc={{ .Values.mgmt.cluster.domain }}"
  - setting: AUTH_LDAP_GROUP_TYPE
    value: "MemberDNGroupType(member_attr='member')"
  - setting: AUTH_LDAP_GROUP_TYPE_PARAMS
    value: {}
