---
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  servingCerts:
    namedCertificates:
    - names:
      - api.{{ .Values.mgmt.apps.domain }}
      servingCertificate:
        name: apiserver-custom-certs
