---
apiVersion: v1
kind: Secret
metadata:
  name: apiserver-custom-certs
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.mgmt.apiserver.tls.crt }}
  tls.key: {{ .Values.mgmt.apiserver.tls.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-custom-certs
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.mgmt.ingress.tls.crt }}
  tls.key: {{ .Values.mgmt.ingress.tls.key }}
