---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "10"
  name: kafka-secret
  namespace: kafka-cluster 
spec:
  template:
    spec:
      containers:
      - image: registry.redhat.io/openshift4/ose-cli:latest 
        command:
        - /bin/bash
        - -c
        - |
          oc wait kafka mano-kafka-cluster --for=condition=ready=true -n kafka-cluster
          mkdir /tmp/kafka
          oc -n kafka-cluster get secret mano-kafka-cluster-cluster-ca-cert -o jsonpath='{.data.ca\.crt}' | base64 -d > /tmp/kafka/ca-bundle.crt
          oc -n kafka-cluster get secret mano-kafka-cluster-clients-ca -o jsonpath='{.data.ca\.key}' | base64 -d > /tmp/kafka/tls.key
          oc -n kafka-cluster get secret mano-kafka-cluster-clients-ca-cert -o jsonpath='{.data.ca\.crt}' | base64 -d > /tmp/kafka/tls.crt
          oc -n openshift-logging delete secret kafka-secret
          oc -n prom-kafka-adapter delete configmap kafka-certs
          oc -n openshift-logging create secret generic kafka-secret --from-file=/tmp/kafka/
          oc -n prom-kafka-adapter create configmap kafka-certs --from-file=/tmp/kafka/
        name: kafka-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: admin-user
      serviceAccountName: admin-user
      terminationGracePeriodSeconds: 400
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kafka-cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kafka-cluster


